### ISSUE TITLE
Tooltip 的回调函数中如何获取到 name

### ISSUE THREAD

**Issue by radicalviva** [alibaba/BizCharts#138]
在官方的示例代码中，也没有提示怎么拿到 name
```
<Chart>
  <Geom
    tooltip={['time*sold', (time, sold) => {
	  return {
	    //自定义 tooltip 上显示的 title 显示内容等。
		name: 'sold',
		title: 'dddd' + time,
		value: sold
	  };
	}]}
  />
</Chart>
```
在多条折线的情况下，我怎么拿到 `name` 呢？

**Comment by BambooSword** [comment]
如果是有多个数据组的情况下就判断传入的数据的key值，如：
![image](https://user-images.githubusercontent.com/18547539/35611071-bfdd8648-069e-11e8-8303-fd31cb73ce7a.png)
这里 key为“日期”：其包含两组数据，根据日期的值的不同来给name赋值。这样就能把name改成我们想要的样子了。 @radicalviva

**Comment by radicalviva** [comment]
@BambooSword 
我知道了 只要在数组里将 3 个参数都传进去就是了

**Comment by mlg87** [comment]
@BambooSword i still dont understand how to get the name of the series set as `name`. [in this screenshot](https://www.dropbox.com/s/tjt8kkw4daa14gx/Screenshot%202018-08-01%2017.01.14.png?dl=0), the tooltip looks correct because it is the default, but in another scenario i would like to add a currency symbol before the `value` (eg. `$234.34`)

**Comment by liunian** [comment]
@mlg87 the simple way is use `formatter(value): any` method in `scale` options, here is an example https://codepen.io/liunian/pen/RBMEoR/

```jsx
const scale = {
  rainfall: {
    formatter(value) {
      return `${value}mm`
    }
  }
};

// ... render react component
<Chart scale={scale} {...otherProps} ..
```
----

If you prefer `tooltip` props in `<Geom />`, you can get series name by first declaring it and then the argument at the same position will be the name of current series.

```jsx
<Geom
	type="interval"
	position="x*y"
	color={'x'}
	tooltip={['x*y', (x, y) => {
	  return {
	    name: x,
	    value: '$' + y
	  }
	}]}
/>
```

And here is an example with tooltip props https://codepen.io/liunian/pen/ajYPmr

**Comment by mlg87** [comment]
@liunian thanks for the quick response. i wasnt aware of the `scale` prop on `Chart`. thank you, that solved my issue. 

for what it's worth, the second solution of configuring the `tooltip` in the `Geom` component doesn't give the desired effect ([see this screenshot](https://www.dropbox.com/s/e1638g7aqxovgfc/Screenshot%202018-08-02%2009.56.14.png?dl=0)). instead of having _Berlin_ and _London_ (the series) listed in the tooltip, it has the month set as the `name`

**Comment by liunian** [comment]
@mlg87 sorry, my mistake, the demo has some problem, we should use `name` field in `tooltip` prop.

actually, the data after transform is something like this:

```js
[
  {
    "name": "London",
    "month": "Jan.",
    "rainfall": 18.9
  },
  {
    "name": "London",
    "month": "Feb.",
    "rainfall": 28.8
  }
]
```

That means we can get city name with `name` field, try visit the updated demo https://codepen.io/liunian/pen/ajYPmr
